"""empty message

Revision ID: 4a1af26a64bb
Revises: 61d856a698f9
Create Date: 2022-11-09 20:52:54.633320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a1af26a64bb'
down_revision = '61d856a698f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
