"""empty message

Revision ID: 61d856a698f9
Revises: a4f8f3472246
Create Date: 2022-11-06 19:19:52.189315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61d856a698f9'
down_revision = 'a4f8f3472246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laps', sa.Column('lap_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('laps', 'lap_number')
    # ### end Alembic commands ###
