"""empty message

Revision ID: 70e987d091c1
Revises: f7abb155e827
Create Date: 2022-04-23 00:11:19.934381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70e987d091c1'
down_revision = 'f7abb155e827'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
