"""empty message

Revision ID: 78f0c6c116a0
Revises: 70e987d091c1
Create Date: 2022-04-25 22:54:40.718973

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '78f0c6c116a0'
down_revision = '70e987d091c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telemetry', sa.Column('MPPT_watts', sa.Float(), nullable=True))
    op.drop_column('telemetry', 'MPPT_watt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telemetry', sa.Column('MPPT_watt', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('telemetry', 'MPPT_watts')
    # ### end Alembic commands ###
