"""empty message

Revision ID: a4f8f3472246
Revises: efdeecec5d4c
Create Date: 2022-10-17 14:34:07.489511

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a4f8f3472246'
down_revision = 'efdeecec5d4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('races', sa.Column('finish_time', sa.DateTime(), nullable=True))
    op.add_column('races', sa.Column('start_pos_lng', sa.Float(), nullable=True))
    op.drop_column('races', 'end_pos_lng')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('races', sa.Column('end_pos_lng', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('races', 'start_pos_lng')
    op.drop_column('races', 'finish_time')
    # ### end Alembic commands ###
