"""empty message

Revision ID: efdeecec5d4c
Revises: 78f0c6c116a0
Create Date: 2022-10-15 19:00:28.964198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efdeecec5d4c'
down_revision = '78f0c6c116a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('races',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('boat_name', sa.String(), nullable=True),
    sa.Column('start_pos_lat', sa.Float(), nullable=True),
    sa.Column('end_pos_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('telemetry', sa.Column('lap_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'telemetry', 'laps', ['lap_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'telemetry', type_='foreignkey')
    op.drop_column('telemetry', 'lap_id')
    op.drop_table('laps')
    op.drop_table('races')
    # ### end Alembic commands ###
