"""empty message

Revision ID: f7abb155e827
Revises: 
Create Date: 2022-04-22 20:34:09.799630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7abb155e827'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telemetry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('controller_watts', sa.Integer(), nullable=True),
    sa.Column('time_to_go', sa.Integer(), nullable=True),
    sa.Column('controller_volts', sa.Float(), nullable=True),
    sa.Column('MPPT_volts', sa.Float(), nullable=True),
    sa.Column('MPPT_watt', sa.Float(), nullable=True),
    sa.Column('motor_temp', sa.Float(), nullable=True),
    sa.Column('motor_revols', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('position_lat', sa.Float(), nullable=True),
    sa.Column('position_lng', sa.Float(), nullable=True),
    sa.Column('distance_travelled', sa.Float(), nullable=True),
    sa.Column('laps', sa.Integer(), nullable=True),
    sa.Column('lap_point_lat', sa.Float(), nullable=True),
    sa.Column('lap_point_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telemetry')
    # ### end Alembic commands ###
